# Generated by Django 4.2.7 on 2026-01-21 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0008_alter_exercise_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="exercise_checks",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object storing exercise check states",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="progress_percentage",
            field=models.IntegerField(
                default=0,
                help_text="Workout completion percentage (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
