# Generated by Django 4.2.7 on 2026-01-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_food_unit_alter_food_serving_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date when this plan ends', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date when this plan becomes active', null=True, verbose_name='Start Date'),
        ),
    ]
